var annotated_dup =
[
    [ "gpio_cfg_t", "structgpio__cfg__t.html", "structgpio__cfg__t" ],
    [ "i2c_req_t", "structi2c__req.html", "structi2c__req" ],
    [ "i2s_cfg_t", "structi2s__cfg__t.html", "structi2s__cfg__t" ],
    [ "mxc_dma_ch_regs_t", "structmxc__dma__ch__regs__t.html", "structmxc__dma__ch__regs__t" ],
    [ "mxc_dma_regs_t", "structmxc__dma__regs__t.html", "structmxc__dma__regs__t" ],
    [ "mxc_flc_regs_t", "structmxc__flc__regs__t.html", "structmxc__flc__regs__t" ],
    [ "mxc_gpio_regs_t", "structmxc__gpio__regs__t.html", "structmxc__gpio__regs__t" ],
    [ "mxc_i2c_regs_t", "structmxc__i2c__regs__t.html", "structmxc__i2c__regs__t" ],
    [ "mxc_icc_regs_t", "structmxc__icc__regs__t.html", "structmxc__icc__regs__t" ],
    [ "mxc_pwrseq_regs_t", "structmxc__pwrseq__regs__t.html", "structmxc__pwrseq__regs__t" ],
    [ "mxc_rtc_regs_t", "structmxc__rtc__regs__t.html", "structmxc__rtc__regs__t" ],
    [ "mxc_spi17y_regs_t", "structmxc__spi17y__regs__t.html", "structmxc__spi17y__regs__t" ],
    [ "mxc_spimss_regs_t", "structmxc__spimss__regs__t.html", "structmxc__spimss__regs__t" ],
    [ "mxc_tmr_regs_t", "structmxc__tmr__regs__t.html", "structmxc__tmr__regs__t" ],
    [ "mxc_uart_regs_t", "structmxc__uart__regs__t.html", "structmxc__uart__regs__t" ],
    [ "mxc_wdt_regs_t", "structmxc__wdt__regs__t.html", "structmxc__wdt__regs__t" ],
    [ "spi17y_req_t", "structspi17y__req.html", "structspi17y__req" ],
    [ "spi_req_t", "structspi__req.html", "structspi__req" ],
    [ "spimss_req_t", "structspimss__req.html", "structspimss__req" ],
    [ "sys_cfg_i2s_t", "structsys__cfg__i2s__t.html", "structsys__cfg__i2s__t" ],
    [ "sys_cfg_rtc_t", "structsys__cfg__rtc__t.html", "structsys__cfg__rtc__t" ],
    [ "sys_cfg_spi17y_t", "structsys__cfg__spi17y__t.html", "structsys__cfg__spi17y__t" ],
    [ "sys_cfg_spimss_t", "structsys__cfg__spimss__t.html", "structsys__cfg__spimss__t" ],
    [ "sys_cfg_tmr_t", "structsys__cfg__tmr__t.html", "structsys__cfg__tmr__t" ],
    [ "sys_cfg_uart_t", "structsys__cfg__uart__t.html", "structsys__cfg__uart__t" ],
    [ "tmr_cfg_t", "structtmr__cfg__t.html", "structtmr__cfg__t" ],
    [ "tmr_pwm_cfg_t", "structtmr__pwm__cfg__t.html", "structtmr__pwm__cfg__t" ],
    [ "uart_cfg_t", "structuart__cfg__t.html", "structuart__cfg__t" ],
    [ "uart_req_t", "structuart__req.html", "structuart__req" ]
];